declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: 'development' | 'production';
      HTTP_SERVER_PORT: number;
      DB_URL: string;
      APP_URL: string;
      JWT_SECRET: string;
      ADMIN_MANAGED_STORES_ENABLED: string;
      ADMIN_PRODUCT_WRITE_ENABLED: string;
      ADMIN_ORDER_WRITE_ENABLED: string;
      ADMIN_BULK_PRODUCT_UPDATE_ENABLED: string;
      ADMIN_MANAGEMENT_SESSION_IDLE_MINUTES: string;
      ADMIN_MANAGEMENT_SESSION_MAX_HOURS: string;
      ADMIN_NAME: string;
      ZONE_STOREFRONTS_ENABLED: string;
      CSRF_SECRET: string;
      CLIENT_URL: string;
      ACCOUNT_SID: string;
      AUTH_TOKEN: string;
      WHATSAPP_PHONE_NUMBER: string;
      WHATSAPP_NOTIFICATIONS_ENABLED: boolean;
      WEBHOOK_PUBLIC_BASE_URL: string;
      TWILIO_CONTENT_SID_NEW_ORDER_MERCHANT: string;
      TWILIO_CONTENT_SID_ORDER_RECEIVED_CUSTOMER: string;
      TWILIO_CONTENT_SID_ORDER_OUT_FOR_DELIVERY: string;
      TWILIO_CONTENT_SID_ORDER_STATUS_UPDATE_CUSTOMER: string;
      TWILIO_CONTENT_SID_MERCHANT_DAY_CLOSURE_SUMMARY: string;
      TWILIO_CONTENT_SID_ZONE_ORDER_OPERATIONS: string;
      TWILIO_CONTENT_SID_ZONE_ORDER_ASSIGNED: string;
      TWILIO_CONTENT_SID_ZONE_DISPATCH_REJECTED_OPERATIONS: string;
      TWILIO_CONTENT_SID_ZONE_DISPATCH_REASSIGNED_OPERATIONS: string;
      TWILIO_CONTENT_SID_ZONE_ORDER_ACCEPTED_CUSTOMER: string;
      TWILIO_VERIFY_SERVICE_SID: string;
      SEED_SUPERMARKET_OWNER_CREDENTIAL: string;
      SENTRY_DSN: string;
    }
  }
}

export {};
