export const EGYPT_DIRECTORY_AREAS = [
  // Giza Areas
  {
    name_ar: 'الشيخ زايد',
    name_en: 'Sheikh Zayed',
    slug: 'sheikh-zayed',
    city: 'Giza',
    governorate: 'Giza',
    sort_order: 100,
    latitude: 30.0131,
    longitude: 30.9766,
  },
  {
    name_ar: 'الخمائل',
    name_en: 'Al Khamayel',
    slug: 'al-khamayel',
    city: 'Sheikh Zayed',
    governorate: 'Giza',
    sort_order: 110,
    latitude: 30.0286,
    longitude: 31.0331,
  },
  {
    name_ar: '6 أكتوبر',
    name_en: '6th of October',
    slug: '6th-of-october',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 200,
    latitude: 29.9668,
    longitude: 30.9279,
  },
  {
    name_ar: 'الحي الأول',
    name_en: '1st District',
    slug: 'october-1st-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 210,
    latitude: 29.983,
    longitude: 30.991,
  },
  {
    name_ar: 'الحي الثاني',
    name_en: '2nd District',
    slug: 'october-2nd-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 220,
    latitude: 29.981,
    longitude: 30.982,
  },
  {
    name_ar: 'الحي الثالث',
    name_en: '3rd District',
    slug: 'october-3rd-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 230,
    latitude: 29.975,
    longitude: 30.975,
  },
  {
    name_ar: 'الحي الرابع',
    name_en: '4th District',
    slug: 'october-4th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 240,
    latitude: 29.97,
    longitude: 30.967,
  },
  {
    name_ar: 'الحي الخامس',
    name_en: '5th District',
    slug: 'october-5th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 250,
    latitude: 29.965,
    longitude: 30.962,
  },
  {
    name_ar: 'الحي السادس',
    name_en: '6th District',
    slug: 'october-6th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 260,
    latitude: 29.951,
    longitude: 30.938,
  },
  {
    name_ar: 'الحي السابع',
    name_en: '7th District',
    slug: 'october-7th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 270,
    latitude: 29.977,
    longitude: 30.945,
  },
  {
    name_ar: 'الحي الثامن',
    name_en: '8th District',
    slug: 'october-8th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 280,
    latitude: 29.981,
    longitude: 30.938,
  },
  {
    name_ar: 'الحي التاسع',
    name_en: '9th District',
    slug: 'october-9th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 290,
    latitude: 29.96,
    longitude: 30.95,
  },
  {
    name_ar: 'الحي العاشر',
    name_en: '10th District',
    slug: 'october-10th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 300,
    latitude: 29.94,
    longitude: 30.93,
  },
  {
    name_ar: 'الحي الحادي عشر',
    name_en: '11th District',
    slug: 'october-11th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 310,
    latitude: 29.945,
    longitude: 30.94,
  },
  {
    name_ar: 'الحي الثاني عشر',
    name_en: '12th District',
    slug: 'october-12th-district',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 320,
    latitude: 29.935,
    longitude: 30.948,
  },
  {
    name_ar: 'الحي المتميز',
    name_en: 'Al Motamayez District',
    slug: 'october-al-motamayez',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 330,
    latitude: 29.9691,
    longitude: 30.9491,
  },
  {
    name_ar: 'غرب سوميد',
    name_en: 'Gharb Somid',
    slug: 'october-gharb-somid',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 340,
    latitude: 29.9786,
    longitude: 30.9694,
  },
  {
    name_ar: 'حدائق أكتوبر',
    name_en: 'Hadayek October',
    slug: 'hadayek-october',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 350,
    latitude: 29.8908,
    longitude: 30.9128,
  },
  {
    name_ar: 'التوسعات الشمالية',
    name_en: 'Northern Expansions',
    slug: 'october-northern-expansions',
    city: '6th of October',
    governorate: 'Giza',
    sort_order: 360,
    latitude: 29.995,
    longitude: 30.965,
  },
  {
    name_ar: 'الدقي',
    name_en: 'Dokki',
    slug: 'dokki',
    city: 'Giza',
    governorate: 'Giza',
    sort_order: 400,
    latitude: 30.0384,
    longitude: 31.2123,
  },
  {
    name_ar: 'المهندسين',
    name_en: 'Mohandessin',
    slug: 'mohandessin',
    city: 'Giza',
    governorate: 'Giza',
    sort_order: 500,
    latitude: 30.0525,
    longitude: 31.2006,
  },
  {
    name_ar: 'الهرم',
    name_en: 'Haram',
    slug: 'haram',
    city: 'Giza',
    governorate: 'Giza',
    sort_order: 600,
    latitude: 29.9874,
    longitude: 31.1429,
  },
  {
    name_ar: 'فيصل',
    name_en: 'Faisal',
    slug: 'faisal',
    city: 'Giza',
    governorate: 'Giza',
    sort_order: 700,
    latitude: 30.0174,
    longitude: 31.2038,
  },
  // {
  //   name_ar: 'العجوزة',
  //   name_en: 'Agouza',
  //   slug: 'agouza',
  //   city: 'Giza',
  //   governorate: 'Giza',
  //   sort_order: 800,
  //   latitude: 30.0603,
  //   longitude: 31.2025,
  // },
  // {
  //   name_ar: 'إمبابة',
  //   name_en: 'Imbaba',
  //   slug: 'imbaba',
  //   city: 'Giza',
  //   governorate: 'Giza',
  //   sort_order: 900,
  //   latitude: 30.0796,
  //   longitude: 31.1984,
  // },
  {
    name_ar: 'حدائق الأهرام',
    name_en: 'Hadayek El Ahram',
    slug: 'hadayek-el-ahram',
    city: 'Giza',
    governorate: 'Giza',
    sort_order: 1000,
    latitude: 29.9713,
    longitude: 31.1024,
  },
] as const;
