export const ActivityActions = {
  TenantStatusChanged: 'tenant.status_changed',
  TenantApplicationApproved: 'tenant.application_approved',
  TenantApplicationRejected: 'tenant.application_rejected',
  OrderCreated: 'order.created',
  OrderStatusChanged: 'order.status_changed',
  OrderCancelled: 'order.cancelled',
  OrderCompleted: 'order.completed',
  OrderRejectedByCustomer: 'order.rejected_by_customer',
  OrderTotalChanged: 'order.total_changed',
  OrderItemPriceChanged: 'order.item_price_changed',
  OrderItemOutOfStock: 'order.item_out_of_stock',
  OrderReplacementProposed: 'order.replacement_proposed',
  OrderReplacementApproved: 'order.replacement_approved',
  OrderReplacementRejected: 'order.replacement_rejected',
  OrderReplacementReset: 'order.replacement_reset',
  ProductCreated: 'product.created',
  ProductUpdated: 'product.updated',
  ProductPriceChanged: 'product.price_changed',
  ProductAvailabilityChanged: 'product.availability_changed',
  ProductArchived: 'product.archived',
  ProductBulkCreated: 'product.bulk_created',
  ProductBulkUpdated: 'product.bulk_updated',
  ProductCsvImportCompleted: 'product.csv_import_completed',
  AdminTenantAccessGranted: 'admin.tenant_access_granted',
  AdminTenantAccessRevoked: 'admin.tenant_access_revoked',
  ManagementSessionStarted: 'management_session.started',
  ManagementSessionEnded: 'management_session.ended',
  ZoneStorefrontCreated: 'zone_storefront.created',
  ZoneStorefrontCatalogSynced: 'zone_storefront.catalog_synced',
  ZoneStorefrontActivationChanged: 'zone_storefront.activation_changed',
  ZoneStorefrontDeliveryFeesChanged: 'zone_storefront.delivery_fees_changed',
  ZoneStorefrontOperatingHoursChanged: 'zone_storefront.operating_hours_changed',
  ZoneStorefrontMerchantChanged: 'zone_storefront.merchant_changed',
  OrderDispatchCreated: 'order_dispatch.created',
  OrderDispatchAssigned: 'order_dispatch.assigned',
  OrderDispatchRejected: 'order_dispatch.rejected',
  OrderDispatchAccepted: 'order_dispatch.accepted',
  OrderDispatchCancelled: 'order_dispatch.cancelled',
  OrderDispatchQuoteChanged: 'order_dispatch.quote_changed',
} as const;

export type ActivityAction =
  (typeof ActivityActions)[keyof typeof ActivityActions];
